### PR TITLE
Modernized to PHP 7.4 code

### PR DESCRIPTION
**Pull request by mbniebergall**
feature/modernize_to_php_7_4 modernized to PHP 7.4 code, including updated guzzle and phpunit, and updated unit tests

I am updating a project to PHP 7.4 and found that php-sfax wasn't compatible, so I updated the code to be compatible with PHP 7.4.

#hacktoberfest-accepted

### CODE REVIEW

**Comment by mikesoule** [comment]
@mbniebergall Thanks for the contribution! I'll get this merged in soon and we'll make it the basis of v2.0. I think I want to remove the `rootwork/phpunit-helpers` dependency as well just to keep it simple and clean.

**Comment by mbniebergall** [comment]
> @mbniebergall Thanks for the contribution! I'll get this merged in soon and we'll make it the basis of v2.0. I think I want to remove the `rootwork/phpunit-helpers` dependency as well just to keep it simple and clean.

Thanks @mikesoule ! Is removing `rootwork/phpunit-helpers` something you have time to work on? If not I can work on it and create a new PR once it is ready. I looked through what it would take and I can certainly update the code to work without it.

**Comment by mikesoule** [comment]
@mbniebergall I would gladly accept a PR for that as well!

**Comment by mikesoule** [comment]
@mbniebergall I created branch [2.0.x](https://github.com/rootworkit/php-sfax/tree/2.0.x) for your recent changes and removing `rootwork/phpunit-helpers`. After removing that package, I'd be happy to tag 2.0.0 for Packagist.

**Comment by mikesoule** [comment]
@mbniebergall How do I do that? As far as I know, anyone can freely create a PR to a public repo like this one.

**Comment by mikesoule** [comment]
@mbniebergall nvmd, just found the guide. It's done!

**Comment by mbniebergall** [comment]
PR for removing `phpunit-helpers` is up, and I'll watch for that to get merged and then packagist to be tagged with 2.0.0. Thank you!

**Pull request merged**
